[workspace]
members = [
  "./analyze",
  "./ir",
  "./opt",
  "./parser",
  "./svelte",
  "./traits",
  "./wasm-api"
]

[profile.release]
lto = true
debug = true

[patch.crates-io.structopt]
git = "https://github.com/fitzgen/structopt.git"
branch = "proc-macro2-nightly-feature-workaround"
